# Generated by Django 3.1.12 on 2026-07-21 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saludya_app', '0002_auto_20260625_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('habit_type', models.CharField(choices=[('hidratacion', 'Hidratación'), ('pausa_activa', 'Pausa Activa'), ('medicacion', 'Medicación')], max_length=20)),
                ('daily_goal', models.FloatField(default=1.0)),
                ('unit', models.CharField(default='veces', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='medicacion',
            name='dosis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicacion',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hidratacion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medicacion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pausaactiva',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recordatorio',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ProgressRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('period', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], max_length=10)),
                ('hydration_pct', models.FloatField(default=0.0)),
                ('pause_pct', models.FloatField(default=0.0)),
                ('medication_pct', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HabitEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='saludya_app.habit')),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('achieved', models.BooleanField(default=False)),
                ('date_awarded', models.DateField(blank=True, null=True)),
                ('icon', models.CharField(default='🏅', max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Actividad Física', 'Actividad Física'), ('Gimnasio', 'Gimnasio'), ('Ciclismo', 'Ciclismo'), ('Caminata', 'Caminata'), ('Estiramiento', 'Estiramiento'), ('Otro', 'Otro')], max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('minutos_caminando', models.IntegerField(default=0)),
                ('minutos_inactividad', models.IntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['categoria', 'fecha', 'hora'],
            },
        ),
    ]
